export const dummy = {
  dates: { maximum: "2023-01-16", minimum: "2022-11-29" },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/r9PkFnRUIthgBp2JZZzD380MWZy.jpg",
      genre_ids: [16, 28, 12, 35, 10751, 14],
      id: 315162,
      original_language: "en",
      original_title: "Puss in Boots: The Last Wish",
      overview:
        "아홉 개의 목숨 중 단 하나의 목숨만 남은 장화신은 고양이.  마지막 남은 목숨을 지키기 위해 히어로의 삶 대신 반려묘의 삶을 선택한 그에게 찾아온 마지막 기회, 바로 소원을 들어주는 소원별이 있는 곳을 알려주는 지도!  잃어버린 목숨을 되찾고 다시 히어로가 되기를 꿈꾸는 장화신은 고양이는 뜻밖에 동료가 된 앙숙 파트너 '키티 말랑손', 그저 친구들과 함께라면 모든 게 행복한 강아지 '페로'와 함께 소원별을 찾기 위해 길을 떠난다.  그리고 소원별을 노리는 또 다른 빌런들과 마주치게 되는데…",
      popularity: 10052.881,
      poster_path: "/rKgvctIuPXyuqOzCQ16VGdnHxKx.jpg",
      release_date: "2023-01-04",
      title: "장화신은 고양이: 끝내주는 모험",
      video: false,
      vote_average: 8.6,
      vote_count: 1893,
    },
    {
      adult: false,
      backdrop_path: "/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
      genre_ids: [878, 12, 28],
      id: 76600,
      original_language: "en",
      original_title: "Avatar: The Way of Water",
      overview:
        "판도라 행성에서 제이크 설리와 네이티리가 이룬 가족이 겪게 되는 무자비한 위협과 살아남기 위해 떠나야 하는 긴 여정과 전투, 그리고 견뎌내야 할 상처에 대한 이야기를 그렸다. 살아남기 위해 설리 가족이 숲에서 바다로 터전을 옮기면서 겪게 되는 화합의 과정, 그리고 곳곳에서 도사리는 새로운 위협까지 역경 속에서 더 아름답게 펼쳐진다.",
      popularity: 2960.254,
      poster_path: "/z56bVX93oRG6uDeMACR7cXCnAbh.jpg",
      release_date: "2022-12-14",
      title: "아바타: 물의 길",
      video: false,
      vote_average: 7.7,
      vote_count: 4304,
    },
    {
      adult: false,
      backdrop_path: "/7dm64SW5L5CCg47kAEAcdCGaq5i.jpg",
      genre_ids: [27, 53],
      id: 676547,
      original_language: "en",
      original_title: "Prey for the Devil",
      overview:
        "과거의 트라우마로 여전히 고통 받고 있는 수녀 앤  구마 의식 학교에서 특별한 재능을 인정받으며 남성 사제에게만 허용되었던 구마 의식 훈련을 받게 되고  그곳에서 만난 환자들을 통해 어릴 적부터 그녀를 괴롭혀 왔던 존재의 실체와 만나게 되는데...",
      popularity: 1123.639,
      poster_path: "/zfWbFiCpi9rlr96hTQpNoqiSKr7.jpg",
      release_date: "2022-12-07",
      title: "프레이 포 더 데블",
      video: false,
      vote_average: 7.2,
      vote_count: 391,
    },
    {
      adult: false,
      backdrop_path: "/mSyQoValhBsJdq3JNGXJww2Q5yL.jpg",
      genre_ids: [35, 27, 53],
      id: 593643,
      original_language: "en",
      original_title: "The Menu",
      overview:
        "커플인 마고와 타일러는 까다롭기로 유명한 셰프, 슬로윅의 초청을 받아 어느 외딴섬 레스토랑의 저녁 식사에 참석하게 된다. 평소 슬로윅을 존경해왔던 타일러는 들뜬 마음으로 여러 유명인사들과 함께 섬으로 출발하는 배에 탑승한다. 레스토랑에 도착한 손님들은 슬로윅의 화려한 환대에 탄성을 자아낸다. 하지만 ‘음식은 또 다른 예술’이라는 슬로윅의 기괴한 집착에, 좋았던 분위기는 점차 이상한 방향으로 흐른다. 뭔가 심상치 않음을 감지한 마고는 이의를 제기하려 하지만, 이미 슬로윅의 음식에 푹 빠져버린 타일러에게 그녀의 제안은 안중에도 없다. 그런 와중에 슬로윅의 기괴한 집착은 점점 선을 넘기 시작하는데...",
      popularity: 404.466,
      poster_path: "/2Bi9OTGNAkNjStDnMDR93GPgwFY.jpg",
      release_date: "2022-12-07",
      title: "더 메뉴",
      video: false,
      vote_average: 7.3,
      vote_count: 1537,
    },
    {
      adult: false,
      backdrop_path: "/atmII0hn3iQe3IWMBmIb3cc8EJZ.jpg",
      genre_ids: [18, 10749, 27],
      id: 791177,
      original_language: "en",
      original_title: "Bones and All",
      overview:
        "열여섯 살이 된 매런은 유일한 가족인 아빠마저 곁을 떠나자 한 번도 보지 못한 엄마를 찾는 길에 오른다. 절망 가운데 자신과 같은 식성을 가진 소년 리를 만나고, 동행하는 길 위에서 사랑을 느끼지만 매런에게 사랑은 늘 파멸과 마찬가지였기에 이 감정을 숨길 수밖에 없다. 평범한 삶을 갈구하는 매런은 리와 끝까지 함께 할 수 있을까? 이 길의 끝에서 매런은 고대하던 것을 찾을 수 있을까?",
      popularity: 139.852,
      poster_path: "/j60Eb7TKqfv0QN8Zn1aKm2DMgbO.jpg",
      release_date: "2022-11-30",
      title: "본즈 앤 올",
      video: false,
      vote_average: 7.5,
      vote_count: 536,
    },
    {
      adult: false,
      backdrop_path: "/4QB2TfxmzgMDLmsVVk1HM4tt7ef.jpg",
      genre_ids: [35, 18, 878],
      id: 744594,
      original_language: "en",
      original_title: "White Noise",
      overview:
        "미국의 조용한 마을에 살고 있는 잭은 대학에서 히틀러를 연구하는 교수이다. 아내와 네 명의 자녀를 둔 그의 인생은 남들처럼 평범하기 그지없다. 어느날, 화학 폐기물을 실은 트럭이 열차와 충돌하는 사고가 발생하면서 마을 전체에 화학 폐기물이 퍼진다. 대피 명령이 내려지면서 평화로웠던 마을은 금세 아수라장이 되고, 사태의 위험성을 깨달은 잭은 가족들과 탈출 행렬에 합류하는데…",
      popularity: 127.263,
      poster_path: "/iaItCRbjr70awVPeaCRUDLPTl80.jpg",
      release_date: "2022-12-07",
      title: "화이트 노이즈",
      video: false,
      vote_average: 5.7,
      vote_count: 267,
    },
    {
      adult: false,
      backdrop_path: "/54PmeEzQMvpojpJBku61ZGQnWUX.jpg",
      genre_ids: [16, 12, 28, 14],
      id: 900667,
      original_language: "ja",
      original_title: "ONE PIECE FILM RED",
      overview:
        "오직 목소리 하나로 전 세계를 사로잡은 디바 ‘우타’.  그녀가 모습을 드러내는 첫 라이브 콘서트가 음악의 섬 ‘엘레지아’에서 열리고  ‘루피’가 이끄는 밀짚모자 해적단과 함께 수많은 ‘우타’ 팬들로 공연장은 가득 찬다.  그리고 이 콘서트를 둘러싼 해적들과 해군들의 수상한 움직임이 시작되는데…  드디어 전세계가 애타게 기다리던 ‘우타’의 등장과 함께 노래가 울려 퍼지고,  그녀가 ‘샹크스의 딸’이라는 충격적인 사실이 드러난다.  ‘루피’, ‘우타’, ‘샹크스’, 세 사람의 과거가 그녀의 노랫소리와 함께 밝혀진다! 여기에서",
      popularity: 126.99,
      poster_path: "/pUEWvgIPGgx0Co9OQUwnKSfxYzQ.jpg",
      release_date: "2022-11-30",
      title: "원피스 필름 레드",
      video: false,
      vote_average: 7.3,
      vote_count: 267,
    },
    {
      adult: false,
      backdrop_path: "/qp8qKiP7Q7zK4z3LItwWMHfV9kJ.jpg",
      genre_ids: [53],
      id: 764835,
      original_language: "en",
      original_title: "The Desperate Hour",
      overview:
        "긴급 경보 : 교내 총격 테러 발생  오전 8:00 에이미는 학교를 가기 싫어하는 아들을 뒤로 한 채 조깅을 나선다. 오전 8:59 아들의 학교에서 총격 테러가 발생했다. 오전 9:00 아들에게 연락이 닿지 않는다. 오전 9:36 아들이 유력한 용의자로 의심받고 있는 것을 알게 된다.  단 한 걸음도, 단 한 순간도 놓치지 못할 리얼 타임 서스펜스가 펼쳐진다!",
      popularity: 77.031,
      poster_path: "/nowGRB6389FFRoGEhq4wsu1GOit.jpg",
      release_date: "2023-01-04",
      title: "패닉 런",
      video: false,
      vote_average: 6.1,
      vote_count: 309,
    },
    {
      adult: false,
      backdrop_path: "/5tb7RjF0OAAaiGDUXsuedvhoGqV.jpg",
      genre_ids: [18, 36],
      id: 837881,
      original_language: "en",
      original_title: "She Said",
      overview:
        "미국의 대표 일간지 뉴욕타임스의 탐사 보도 취재 기자 메건 투히와 조디 캔터는 모두가 침묵하고 있던 할리우드의 악마 하비 와인스타인의 성추문 의혹을 취재하기 시작한다. 하지만 굳게 입을 다문 피해자들과 오히려 가해자를 보호하는 시스템이 이들을 막아서고 진실에 파고들던 두 사람은 생명의 위협까지 받게 되는데... 세상의 변화를 이끌어낸 이들의 집요한 진실 추적기가 시작된다.",
      popularity: 71.257,
      poster_path: "/c4vgMNRhPMFnruvlTjTC27yaQd3.jpg",
      release_date: "2022-11-30",
      title: "그녀가 말했다",
      video: false,
      vote_average: 7.3,
      vote_count: 174,
    },
    {
      adult: false,
      backdrop_path: "/zjpYDQlhvrAaohKRShu522sKJ87.jpg",
      genre_ids: [16, 35, 18],
      id: 783675,
      original_language: "ja",
      original_title: "THE FIRST SLAM DUNK",
      overview:
        "전국 제패를 꿈꾸는 북산고 농구부 5인방의 꿈과 열정, 멈추지 않는 도전을 그린 영화",
      popularity: 87.489,
      poster_path: "/coiJrdXAXuBkSGDvp9bZ7mkuU6E.jpg",
      release_date: "2023-01-04",
      title: "더 퍼스트 슬램덩크",
      video: false,
      vote_average: 8.2,
      vote_count: 10,
    },
    {
      adult: false,
      backdrop_path: "/9VIURlZvfnmFACs2m0MdUDDC3In.jpg",
      genre_ids: [14, 18, 10749],
      id: 556694,
      original_language: "en",
      original_title: "Three Thousand Years of Longing",
      overview:
        "세상 모든 이야기에 통달한 서사학자 알리테아가 우연히 소원을 이뤄주는 정령 지니를 깨워낸다. 그녀에게 주어진 기회는 단 세 번. 마음속 가장 깊은 곳, 가장 오랫동안 바라온 소원을 말할 것!",
      popularity: 58.658,
      poster_path: "/hHmJGgb29sIxSK9EOf6d68mDnEM.jpg",
      release_date: "2023-01-04",
      title: "3000년의 기다림",
      video: false,
      vote_average: 7.1,
      vote_count: 609,
    },
    {
      adult: false,
      backdrop_path: "/r6aqhlmJmu8Dv5E7QYEruaEXKYm.jpg",
      genre_ids: [18],
      id: 758866,
      original_language: "ja",
      original_title: "ドライブ・マイ・カー",
      overview:
        "누가 봐도 아름다운 부부 가후쿠와 오토.  우연히 아내의 외도를 목격한 가후쿠는 이유를 묻지 못한 채 갑작스럽게 아내의 죽음을 맞이하게 된다. 2년 후 히로시마의 연극제에 초청되어 작품의 연출을 하게 된 가후쿠. 그는 그곳에서 자신의 전속 드라이버 미사키를 만나게 된다. 말없이 묵묵히 가후쿠의 차를 운전하는 미사키와 오래된 습관인 아내가 녹음한 테이프를 들으며 대사를 연습하는 가후쿠. 조용한 차 안에서 두 사람은 점점 마음을 열게 되고, 서로가 과거의 아픔에서 벗어나지 못한 것을 알게 된다.  그리고 눈 덮인 홋카이도에서 내면에 깊숙이 자리 잡은 서로의 슬픔을 들여다보게 되는데….",
      popularity: 20.238,
      poster_path: "/5L1SKj1UyDE4rmRNtY1RwFdRhe7.jpg",
      release_date: "2021-12-23",
      title: "드라이브 마이 카",
      video: false,
      vote_average: 7.4,
      vote_count: 859,
    },
    {
      adult: false,
      backdrop_path: "/9BQPM1Fa1hdXaE7hNafO5WWNv9v.jpg",
      genre_ids: [27, 53],
      id: 631947,
      original_language: "en",
      original_title: "La Llorona",
      overview:
        "변화를 위해 특별히 멕시코로 휴가를 떠난 ‘칼리’ 가족. 하지만 그들이 머무는 곳에 밤마다 아이들이 종종 사라진다. 아이를 데려간다는 멕시코의 전설적인 귀신 요로나, 그녀의 저주가 점차 다가오기 시작하고 결국 칼리의 아들 ‘대니’가 요로나에게 납치당해 행방불명된다. 사라진 아들을 찾기 위해 ‘칼리’ 부부는 요로나에 맞서기로 하는데…  과연 그들은 요로나의 저주로부터 벗어날 수 있을 것인가?",
      popularity: 19.11,
      poster_path: "/seAK7B5ZuWhQ1h6CtWEhXsMPcTM.jpg",
      release_date: "2022-12-30",
      title: "요로나: 끝나지 않은 저주",
      video: false,
      vote_average: 4.7,
      vote_count: 36,
    },
    {
      adult: false,
      backdrop_path: "/cuyXEls6uOMDqflx2MSzZOuQSn2.jpg",
      genre_ids: [35, 18],
      id: 668640,
      original_language: "es",
      original_title: "Competencia oficial",
      overview:
        "가진 것 없이 맨손으로 시작해 자수성가한 억만장자. 세상의 모든 부귀영화를 누리지만 명성에 목마른 그는 80세 생일 기념으로, ‘훌륭한 영화’를 만들라고 지시한다. 노벨문학상 판권을 돈으로 사버리고 전 세계 영화제를 휩쓴 경력을 지닌 ‘롤라 쿠에바스’를 감독으로 기용한다. 천재 감독으로 불리지만 괴짜 기질이 있다고 알려진 ‘롤라 쿠에바스’ 감독은, 자신이 연출할 영화에 연기 거장 ‘이반 토레스’와 월드 스타 ‘펠릭스 리베로’를 캐스팅한다.  넘쳐흐르는 제작비로 최고의 원작, 최고의 감독, 최고의 배우가 뭉치고, 지상 최대의 걸작 만들기 프로젝트가 시작된다!",
      popularity: 22.384,
      poster_path: "/z5UWRwfh04cPNaKpXpvqUfIoJdq.jpg",
      release_date: "2022-12-28",
      title: "크레이지 컴페티션",
      video: false,
      vote_average: 6.8,
      vote_count: 229,
    },
    {
      adult: false,
      backdrop_path: "/mgDv2dDihyetAcENxyf2tpXY245.jpg",
      genre_ids: [10402, 18],
      id: 1407,
      original_language: "fr",
      original_title: "La Môme",
      overview:
        "1925년 프랑스, 10살 어린 소녀의 노래 소리가 사람들을 사로잡는다. 노래의 주인공은 바로 훗날 전세계를 사로잡은 20세기 최고의 가수 에디트 삐아프. 거리의 가수였던 어머니에게 버림받고 서커스 단원 아버지를 따라 방랑생활을 하다 거리에서 노래를 부르며 하루하루를 연명하던 20살 그녀 앞에 행운이 찾아온다. 에디트의 목소리에 반한 루이스 레플리의 클럽에서 ‘작은 참새’라는 뜻의 ‘삐아프’라는 이름과 함께 성공적인 데뷔 무대를 갖게 된 것. 열정적인 그녀의 노래에 반한 사람들이 에디트에 열광하기 시작할 무렵, 그녀를 발굴한 루이스 레플리가 살해되면서 뜻밖의 시련을 겪게 된다.",
      popularity: 14.926,
      poster_path: "/iPhDNKwTX7LPECxfLUcW5Kf3kkK.jpg",
      release_date: "2007-11-21",
      title: "라 비 앙 로즈",
      video: false,
      vote_average: 7.5,
      vote_count: 1395,
    },
    {
      adult: false,
      backdrop_path: "/kgP4YOUWKhJZWL0Z8LJ6G6LBMEM.jpg",
      genre_ids: [10752, 18],
      id: 581577,
      original_language: "de",
      original_title: "Persian Lessons",
      overview:
        "페르시아어를 배우기 원하는 독일군 장교 코흐. 살기 위해 페르시아인이라고 거짓말을 한 유대인 질. 질은 살아남기 위해 코흐에게 가짜 페르시아어를 가르치고 매일 밤 거짓으로 단어를 만드는데...",
      popularity: 19.457,
      poster_path: "/bem8vujUVBBhd7ktTs90X3zzWtm.jpg",
      release_date: "2022-12-15",
      title: "페르시아어 수업",
      video: false,
      vote_average: 7.7,
      vote_count: 281,
    },
    {
      adult: false,
      backdrop_path: "/iWz8VTQaimKmC6MEYWa0uhyrW9p.jpg",
      genre_ids: [53, 9648, 18, 80],
      id: 750253,
      original_language: "en",
      original_title: "My Son",
      overview:
        "워커홀릭 석유 엔지니어 ‘에드먼드 머레이’(제임스 맥어보이)는 이혼한 아내 ‘조앤’(클레어 포이)과 함께 살고 있던 아들 ‘이든’이 실종되었다는 전화를 받는다.  충격에 휩싸인 그는 가족이 함께 살았던 집으로 되돌아오고, 아들이 단순 실종이 아닌, 납치되었다는 단서를 찾게 된다.  수사과정은 더디고 사건을 향한 의문의 방해까지 받자 더 이상 경찰도, 그 누구도 믿지 못하게 된 에드먼드는 아들을 되찾기 위한 직접 나서기 시작하는데…  모든 것이 의심스러운 상황 속에서, 수단과 방법을 가리지 않고 납치된 아들을 찾아야 한다!",
      popularity: 16.175,
      poster_path: "/7IghoT2l3SAJSWSGK40tYCJ0B3e.jpg",
      release_date: "2022-12-08",
      title: "마이 선",
      video: false,
      vote_average: 6.2,
      vote_count: 323,
    },
    {
      adult: false,
      backdrop_path: "/p9R163gjE6Z5g4eWY1qnvU4vbW2.jpg",
      genre_ids: [18, 36],
      id: 888321,
      original_language: "de",
      original_title: "Corsage",
      overview:
        "유럽에서 가장 아름다운 여인으로 유명한 오스트리아의 황후 엘리자베트. 그에게 주어진 역할은 1킬로의 머리를 이고 우아하게 앉아있는 것뿐이다. 갑갑한 황실에서 벗어나고 싶은 엘리자베트는 자유를 찾아 자신을 조이던 코르사주를 벗고 스스로의 초상을 완성하려 한다.",
      popularity: 17.415,
      poster_path: "/mmWB2sfDFaMDS2N0kNHRkuQZqTK.jpg",
      release_date: "2022-12-21",
      title: "코르사주",
      video: false,
      vote_average: 7,
      vote_count: 65,
    },
    {
      adult: false,
      backdrop_path: "/rTefIDfreT1kcjuld8K1wgI3ifp.jpg",
      genre_ids: [16, 12, 35, 10751, 14, 10402],
      id: 354279,
      original_language: "en",
      original_title: "Charming",
      overview:
        '세상의 모든 공주들이 동시에 반한 치명적인 매력의 왕자가 나타났다!  사악한 마녀의 저주로 세상 모든 여자를 한눈에 반하게 만드는 ‘매력 저주’에 걸린 챠밍 왕자. 치명적인 매력으로 신데렐라, 백설공주, 잠자는 숲 속의 공주 모두와 동시에 약혼하는 왕국 초유의 사태가 벌어지는데… 어둠의 마법을 풀고 나쁜 남자의 누명을 벗으려면 단 하나의 진정한 사랑을 찾아야만 한다. 챠밍 왕자는 유일하게 ‘매력 저주’가 통하지 않는 의문의 여도둑 ‘레노어’를 호위병으로 삼아 진정한 사랑을 찾기 위해 함께 모험을 떠난다.  우리가 알던 동화의 완벽한 반전! "슈렉" 제작진이 선사하는 최고의 판타지 매직버스터가 온다!',
      popularity: 16.612,
      poster_path: "/4MWDelm4AICgZ86ZblD86RugEp9.jpg",
      release_date: "2023-01-11",
      title: "프린스 챠밍",
      video: false,
      vote_average: 6.5,
      vote_count: 220,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18],
      id: 1069049,
      original_language: "ko",
      original_title: "열여덟, 어른이 되는 나이",
      overview:
        "\"나한테 별로 고마워하지 않아도 돼요\" 까칠한 어른 윤서, \"한 번 쯤은 자기를 믿어주는 사람이 있으면 좋잖아요\" 꿈 없는 청년 수찬.  시청 정기간행물의 인터뷰어 '윤서'에게 사람의 온기는 한여름의 습하고 불쾌한 더위 같은 것. 그러던 어느 날, 청년 배달원 '수찬'과 실랑이를 벌이고 만다. 이후 인터뷰 자리에서 우연찮게 다시 만나게 되는데...  윤서와 수찬, 두 사람의 불편한 만남은 조금씩 서로를 건드린다.",
      popularity: 9.523,
      poster_path: "/xLyvxKHYC4RL8jasp83rQD4oHX.jpg",
      release_date: "2023-01-15",
      title: "열여덟, 어른이 되는 나이",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
  ],
  total_pages: 4,
  total_results: 76,
};
